name: Release Rust

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    permissions:  # 添加权限设置
        contents: write  # 允许读写仓库内容    
    runs-on: ${{ matrix.os }}
    strategy:
      # matrix上下文，包含在工作流中定义的应用于当前作业的矩阵属性
      matrix:
        # 你可以添加更多你想要的构建平台
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            path: jvm

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            path: jvm


          - build: win-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            path: jvm.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Rust
        uses: taiki-e/upload-rust-binary-action@v1.27.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
          tar: unix
          zip: windows